-- IS Performance OS - Ficha completa de insumos (etiquetado) + importar desde Químicos
-- Pegar en Supabase > SQL Editor > Run.
alter table productos add column if not exists familia      text; -- grupo / uso (PRELAV, VIDRIOS, INTERIOR…)
alter table productos add column if not exists presentacion text; -- envase: Bidón, Galón, Spray, Kg…
alter table productos add column if not exists contenido    text; -- tamaño del envase: 5 L, 1 L, 500 ml…
alter table productos add column if not exists ubicacion    text; -- dónde está en bodega: Estante A, Box lavado…
