-- ============================================================
-- IS Performance OS - Código SKU por producto (Stock)
-- Esquema: <prefijo 2 díg.><correlativo>  ej. 3100001  (31 + 5 dígitos)
--   3x = Insumos     · 4x = En venta / Equipamiento
--   Insumos:  31 Químico · 32 Insumo · 33 Máquina/Herramienta
--             34 Repuesto · 39 Otro
--   En venta: 41 Equipamiento · 42 Detailing · 49 Otro
--   (el formato se edita en la app: SKU_DIGITOS y skuPrefijo en index.html)
-- Los códigos se generan desde la app (botón "Generar SKU" en Stock, y
-- automáticamente al agregar un producto nuevo).
-- Pegar en Supabase > SQL Editor > Run. Seguro de re-ejecutar.
-- ============================================================
alter table productos add column if not exists sku text;
